### ISSUE TITLE
Consultar el diccionario sin internet

### ISSUE THREAD

**Issue by moshpirit** [javierllorente/adc#1]
¿hay alguna forma de descargar y leer el diccionario y utilizarlo con la aplicación estando desconectado de internet? a mí personalmente me valdría mucho más la pena descargarme el contenido y guardarlo en el teléfono, ya que la respuesta sería más rápida, sin cookies, JS, etc y por supuesto, supondría que se podría consultar en la calle sin necesidad de datos o WiFi.

¡Un saludo y muchísimas gracias por la aplicación!

**Comment by javierllorente** [comment]
Si consultas una definición, se queda en la caché. Ese término ya lo tendrías en el móvil, pero claro no tiene mucha gracia el tema.

¿Te refieres a descargarte todas las definiciones del diccionario? Ocuparía un montón y las definiciones son propiedad de la RAE (no se pueden redistribuir, ya sabes).

Saludos

**Comment by moshpirit** [comment]
Me refiero efectivamente a descargar todas las definiciones. Lo que no entiendo entonces es cómo se crean aplicaciones de diccionarios si realmente es contenido con derecho de autor aunque, como dices, es verdad que tienen ese derecho. En todo caso habría que coger las definiciones de Wiktionary o alguna otra plataforma similar (aunque no sea la RAE, claro). Personalmente, a mí la opción de descargar dicho diccionario me parece una ventaja de todos modos.

**Comment by javierllorente** [comment]
Usando un navegador empotrado, por ejemplo. En ese caso sólo las estarías mostrando, no redistribuyendo. Coger las definiciones de Wiktionary o similares ya sería otra historia.
